#!/bin/bash 

name: Update table every 5 minutes
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  build:
    name: Update first comment
    runs-on: ubuntu-latest
    steps:
      - name: path
        run:
          echo $(cat /github/home/data.txt)
      - name: Find first comment
        uses: peter-evans/find-comment@v1
        id: fc
        with:
          issue-number: $(cat /github/home/data.txt) 
          comment-author: 'github-actions[bot]'
      - name: Print comment-ID
        run: echo "${{ steps.fc.outputs.comment-id }}"

      - name: Update comment
        uses: jungwinter/comment@v1
        with:
          type: edit
          body: |
            
            Toplist (updated every 5 min):

            ...
          comment_id: ${{ steps.fc.outputs.comment-id }}
          token: ${{ secrets.GITHUB_TOKEN }}
