name: Upvote

on:
  pull_request_target: 
    types: [labeled]

jobs:
  new_issue:
    
      if: ${{ github.event.label.name == 'Upvote - Course Automation' }} && ${{ github.repository == 'Renstrom/upvote'}}
      runs-on: ubuntu-latest
      name: Create an issue if none exists
      steps:
        - uses: actions/checkout@v2
        - uses: nickderobertis/check-if-issue-exists-action@master
          name: Check if Issue Exists
          id: check_if_issue_exists
          with:
            repo: ${{ github.repository }}
            token: ${{ secrets.GITHUB_TOKEN }}
            title: "Upvote projects - Course Automation"
            labels:
        - name: Create Issue    
          uses: JasonEtco/create-an-issue@v2
          env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
              update_existing: true
          id: issue
        - name: Create comment
          uses: peter-evans/create-or-update-comment@v1
          with:
            issue-number: ${{ steps.issue.outputs.number }}
            body: |
              Title of pull request: ${{ github.event.pull_request.title }}
              Link to pull request: ${{ github.event.pull_request.html_url }}
              You can view the repository [here](https://github.com/${{github.event.pull_request.head.repo.full_name}}/tree/${{ github.head_ref }})      
        - name: Checkout
          uses: actions/checkout@v1
        - name: Comment on PR
          uses: thollander/actions-comment-pull-request@master
          with:
            message: 'A comment has been added to the following thread: #${{ steps.issue.outputs.number }}. People can now upvote your project!'
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        - name: Test json echo
          id: commentid 
          run: |
        
            curl -s https://api.github.com/repos/Renstrom/upvote/issues/${{ steps.issue.outputs.number }}/comments | jq -c '.[].id' | while read id ; do
                echo "$(curl -H "Accept: application/vnd.github.squirrel-girl-preview+json" https://api.github.com/repos/Renstrom/upvote/issues/comments/${id}/reactions) | jq -c '.[] | select (.[].content=="+1")'  "
            done
           
    


