name: Upvote

on:
  pull_request: 
    types: [labeled]

jobs:
  new_issue:
    
      if: ${{ github.event.label.name == 'Upvote - Course Automation' }}
      runs-on: ubuntu-latest
      name: Create an issue if none exists
      steps:
        - uses: actions/checkout@v2
        - uses: nickderobertis/check-if-issue-exists-action@master
          name: Check if Issue Exists
          id: check_if_issue_exists
          with:
            repo: dmariel/upvote
            token: ${{ secrets.GITHUB_TOKEN }}
            title: "Upvote projects - Course Automation"
            labels:
        - name: Create Issue    
          uses: JasonEtco/create-an-issue@v2
          env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
              update_existing: true
          id: issue
        - name: Create comment
          uses: peter-evans/create-or-update-comment@v1
          with:
            issue-number: ${{ steps.issue.outputs.number }}
            body: |
              Title of pull request: ${{ github.event.pull_request.title }}
              Link to pull request: ${{ github.event.pull_request.html_url }}
              Link to pull reques testt: ${{ github.event.pull_request.repo.branches_url}}

              You can view the repository [here](https://github.com/${{ github.repository }})
        - name: Checkout
          uses: actions/checkout@v1
        - name: Comment on PR
          uses: thollander/actions-comment-pull-request@master
          with:
            message: 'A comment has been added to the following thread: #${{ steps.issue.outputs.number }}. People can now upvote your project!'
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        

