name: Upvote

on:
  pull_request: 
    types: [labeled]

jobs:
  new_issue:
    
      if: ${{ github.event.label.name == 'Upvote - Course Automation' }}
      runs-on: ubuntu-latest
      name: Create an issue if none exist
      steps:
        - uses: actions/checkout@v2
        - uses: nickderobertis/check-if-issue-exists-action@master
          name: Check if Issue Exists
          id: check_if_issue_exists
          with:
            repo: Renstrom/upvote
            token: ${{ secrets.GITHUB_TOKEN }}
            title: "Upvote projects - Course Automation"
        - name: Create Issue    
          if: steps.check_if_issue_exists.outputs.exists == 'false'
          uses: JasonEtco/create-an-issue@v2
          env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          id: issue
        - name: Create comment
          uses: peter-evans/create-or-update-comment@v1
          with:
            issue-number: ${{ steps.issue.outputs.number }}
            body: |
              Title of pull request - ${{ github.event.pull_request.title }}
              URL - ${{ github.event.pull_request.html_url }}


